# Generated by Django 3.2.8 on 2021-10-26 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yarns.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=280)),
                ('upload', models.FileField(blank=True, null=True, upload_to=yarns.models.blogger_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blogger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('parent_yarn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yarns.yarn')),
                ('re_yarn', models.ManyToManyField(blank=True, related_name='reyarn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'yarn',
                'verbose_name_plural': 'yarnings',
                'ordering': ['-created'],
            },
        ),
    ]
